[package]
name = "discordant"
version = "0.1.0"
authors = ["Kixiron <contact.kixiron@gmail.com>"]
edition = "2018"

[dependencies]
serenity = { git = "https://github.com/Kixiron/serenity" }
dotenv = "0.14.1"
serde_json = "1.0.40"
